---
name: Bump Version
description: Bumps version in pyproject.toml using commitizen

inputs:
  github_token:
    description: Token to authenticate with GitHub
    required: true
    type: string

runs:
  using: docker
  image: Dockerfile
