---
name: Bump Version
description: Bumps version in pyproject.toml using commitizen

inputs:
  machine_user_pat:
    description: A GitHub Personal Access Token (PAT) with repo access
    required: true

runs:
  using: docker
  image: Dockerfile
