---
name: Release

on:
  push:
    branches:
      - main
    paths:
      - "!**"
      - CHANGELOG.md
      - pyproject.toml

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          version: 1.6.1

      - name: Install Python Dependencies with Poetry
        shell: bash
        run: poetry install

      - name: Get version
        id: get-version
        shell: bash
        run: |
          echo "tag=$(poetry version --short)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.get-version.outputs.tag }}
          name: ${{ steps.get-version.outputs.tag }}
          generateReleaseNotes: true

      - name: Update Latest Tag
        uses: EndBug/latest-tag@v1
        with:
          ref: latest

      - name: Extract Major Version
        shell: bash
        id: extract_major_version
        run: |
          echo "tag=$(poetry version --short | cut -d '.' -f1)" >> $GITHUB_OUTPUT

      - name: Update Major Tag
        uses: EndBug/latest-tag@v1
        with:
          ref: ${{ steps.extract_major_version.outputs.tag }}
